enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  eslint-config-neon@*:
    peerDependenciesMeta:
      eslint:
        optional: true
      svelte:
        optional: true
      typescript:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
